### ISSUE TITLE
能增加C#调用的例子吗？

### ISSUE THREAD

**Issue by OctoberKey** [thejinchao/AxTrace#2]
像老版本那样，谢谢。

**Comment by longlongvip** [comment]
贴一下网友 OctoberKey 的 `C#` 实现，[C#](https://www.cnblogs.com/octoberkey/p/14778145.html)

**Comment by longlongvip** [comment]
此 issue 应该可以关闭了

**Comment by thejinchao** [comment]
这个工程好久没看过了，谢谢 @longlongvip
